const category_data = [
    {
        cat_id: "1",
        cat_name: "men"
    },
    {
        cat_id: "2",
        cat_name: "women"
    },
    {
        cat_id: "3",
        cat_name: "kids"
    }
];

const subcategory_data = [
    {
        cat_id: "1",
        sub_cat_id: "101",
        sub_cat_name: "t-shirts"
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        sub_cat_name: "jeans"
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        sub_cat_name: "shoes"
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        sub_cat_name: "jacket"
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        sub_cat_name: "accessories"
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        sub_cat_name: "sarees"
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        sub_cat_name: "top"
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        sub_cat_name: "jeans"
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        sub_cat_name: "shoes"
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        sub_cat_name: "jewellery"
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        sub_cat_name: "cloths"
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        sub_cat_name: "toys"
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        sub_cat_name: "school stationery"
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        sub_cat_name: "shoes"
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        sub_cat_name: "winter wear"
    },
];

const Product_data = [
    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1151",
        product_name:"Kalapuri Women's Ready To Wear Nauwari Silk Saree Without Blouse Piece",
        product_description: "Traditional Readymade Nauvari Saree, Matching borders for blouse sleeves || Material: Belgaum Catlon || Size: Height 40 Inch, Hip size suitable for 34-42 Inch || Easy to wear and Comfortable like Salwar.",
        product_rating: "3.5",
        product_rating_count: "101",
        product_img: "https://m.media-amazon.com/images/I/61eY2UrLGCL._SX679._SX._UX._SY._UY_.jpg",
        product_price: "3,599",
        product_discount_price: "1,799",
        product_discount_percentage: "50 ",
        product_color: "Yellow",
        product_size: "Regular fit",
        recently_view: true,
        trending_product: true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1152",
        product_name:"Pandadi Saree Women's Paithani Silk Saree With unstitched Blouse Piece", 
        product_description: "Saree Fabric : Art Silk || Saree Length :6.3 Mtrs Including Blouse (5.5 mts+ 80 cm Blouse ).",
        product_rating:"3.9",
        product_rating_count:"53",
        product_img: "https://m.media-amazon.com/images/I/91hQBa9RUbL._UY879_.jpg",
        product_price: "2,999",
        product_discount_price: "1,499",
        product_discount_percentage: "50 ",
        product_color:"Pink-orange",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1153",
        product_name:"Sidhidata Women's Kanjivaram Saree With Blouse Piece",
        product_description:"Care Instructions: Machine Wash || Saree Fabric : Banarasi Silk || Saree Length : 6.3 Mtr included Blouse Piece || Work Type : Woven Floral design All over / Soft Finished /Comfortable to wear",
        product_rating:"4.5",
        product_rating_count:"758",
        product_img: "https://m.media-amazon.com/images/I/91HAgnw2CTL._UX679_.jpg",
        product_price: "895",
        product_discount_price: "895",
        product_discount_percentage: "0 ",
        product_color:"Pink",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1154",
        product_name:"Sidhidata Textile Women's Dola Silk Foil Printed Saree With Unstitched Blouse Piece",
        product_description:"Care Instructions: hand wash || Fabric : Dola Silk || Type : Foil Printed || Design : Leheriya || Saree Length : 5.5 Mtr + Blouse Length : 0.80 Mtr (Unstitched)",
        product_rating:"3.5",
        product_rating_count:"234",
        product_img: "https://m.media-amazon.com/images/I/710Gqx1n91L._UY879_.jpg",
        product_price: "2,999",
        product_discount_price: "749",
        product_discount_percentage: "75 ",
        product_color:"Rama Green",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1155",
        product_name:"Sidhidata Women's Full Crushed/Pleated Satin Saree With Unstitched Blouse Piece",
        product_description:"Care Instructions: hand wash || Fabric : Heavy Satin || Type : Crushed/ Pleated Saree || Design : Plain/Solid || Saree Length : 5.6 Mtr + Blouse Length : 0.80 Mtr (Unstitched)",
        product_rating:"4.1",
        product_rating_count:"652",
        product_img: "https://m.media-amazon.com/images/I/71+1MFT-tvL._UX679_.jpg",
        product_price: "2,499.00",
        product_discount_price: "599.00",
        product_discount_percentage: "76 ",
        product_color:"Dark Green",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1156",
        product_name:"L G FASHION Womens Lycra Ready To Wear Saree with UnStitched Blouse",
        product_description:"Ready To Wear Saree || Length : Saree Length is 5.5 Meter With UnStitched Blouse. There might be minor colour variation between actual product and image shown on screen due to lighting on the photography",
        product_rating:"3.3",
        product_rating_count:"14",
        product_img: "https://m.media-amazon.com/images/I/71w5gCBq7OL._SY879._SX._UX._SY._UY_.jpg",
        product_price: "2,199.00",
        product_discount_price: "799.00",
        product_discount_percentage: "64 ",
        product_color:"Grey",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1157",
        product_name:"Indian Youth Women's Net Saree With Blouse Piece",
        product_description:"Saree Length: 5.50 Mtr || Blouse Length: 0.80 Mtr || Saree Fabric: Georgette || Blouse: Banglory Beautifully applique Work Self style Saree || Occasion : Casual & festive || fashionable latest design Beautifully Women Saree Multi colors",
        product_rating:"3.6",
        product_rating_count:"19",
        product_img: "https://m.media-amazon.com/images/I/812nLExAIvS._UY879_.jpg",
        product_price: "4,999.00",
        product_discount_price: "1,000.00",
        product_discount_percentage: "80",
        product_color:"Red",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1158",
        product_name:"Market Magic World Women's Satin Silk Shiny Saree with Brocade Blouse (FreeSize_More Color Available)",
        product_description:"Saree length: 5.50 m || Blouse length: 0.90 m || content - 1 saree with 1 blouse piece",
        product_rating:"3.9",
        product_rating_count:"704",
        product_img: "https://m.media-amazon.com/images/I/71pMN2t0nnL._UY879_.jpg",
        product_price: "899.00",
        product_discount_price: "499.00",
        product_discount_percentage: "44 ",
        product_color:"Black",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1159",
        product_name:"Kiaaron Women's Ikat Hand Block Print Jaipuri Cotton Mulmul Saree with Blouse Piece",
        product_description:"Beautiful Traditional Ethnic Indian Wear Saree with Blouse Piece. This Saree gives an Ethnic Indian look. This sari is great for wearing purposes. Work: Printed, Block print, Traditional Ethnic Look",
        product_rating:"4.3",
        product_rating_count:"325",
        product_img: "https://m.media-amazon.com/images/I/31jzFQLaWfL.jpg",
        product_price: "6,999.00",
        product_discount_price: "799.00",
        product_discount_percentage: "89 ",
        product_color:"Yellow & black",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1160",
        product_name:"Shivanya Handicrafts Women's Hand block printed cotton mulmul fabric saree With Blouse Piece",
        product_description:"Beautiful Traditional Ethnic Indian Wear Saree with Blouse Piece .This Saree gives Ethnic Indian look. This sari is great for wearing purpose.",
        product_rating:"4",
        product_rating_count:"319",
        product_img: "https://m.media-amazon.com/images/I/713qMkLcfoS._UX679_.jpg",
        product_price: "2,799.00",
        product_discount_price: "799.00",
        product_discount_percentage: "71 ",
        product_color:"White 4",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1161",
        product_name:"Lymio Women's Regular Top",
        product_description:"Care Instructions: Dry Clean Only || Fabric : Chiffon ||Sleeve Type : 3/4th Sleeve",
        product_rating:"4.5",
        product_rating_count:"477",
        product_img: "https://m.media-amazon.com/images/I/61CD7jRIVRL._AC_UL480_FMwebp_QL65_.jpg",
        product_discount_price: "389.00",
        product_price: "1,799.00",
        product_discount_percentage: "74 ",
        product_color:"Green",
        product_size:"Regular fit",
        recently_view:true, 
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1162",
        product_name:"Wedani Women's Casual Puff Sleeves Ruffled Collor Foral Top",
        product_description:"Fabric: Rayon||Sleeve Type: Short Sleeve || Collar Style: Classic Collar",
        product_rating:"3",
        product_rating_count:"216",
        product_img: "https://m.media-amazon.com/images/I/71sm8MRnZ2L._AC_UL480_FMwebp_QL65_.jpg",
        product_discount_price: "259.00",
        product_price: "1,299.00",
        product_discount_percentage: "80 ",
        product_color:"Dark-Pink",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1163",
        product_name:"Aahwan Women's & Girls' Solid Asymmetrical Neck Cotton Rib Cut Out Crop Top",
        product_description:"Care Instructions: Machine Wash || Material: 95  Cotton 5  Polyester || Sleeve: Sleeveless",
        product_rating:"4",
        product_rating_count:"177",
        product_img: "https://m.media-amazon.com/images/I/7192ExRoKWL._AC_UL480_FMwebp_QL65_.jpg",
        product_discount_price: "329.00",
        product_price: "999.00",
        product_discount_percentage: "67 ",
        product_color:"Beige",
        product_size:"Slim fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1164",
        product_name:"Rajovati Women Puff Sleeve Tops",
        product_description:"Care Instructions: hand wash only || Fabric :Made of high quality Cotton Lycra Blend",
        product_rating:"4",
        product_rating_count:"234",
        product_img: "https://m.media-amazon.com/images/I/51G5HkHfmOL._AC_UL480_FMwebp_QL65_.jpg",
        product_discount_price: "379.00",
        product_price: "1999.00",
        product_discount_percentage: "81 ",
        product_color:"White",
        product_size:"Slim fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1165",
        product_name:"SIGHTBOMB Ribbed Polo Collar Extended Sleeves Tops for Women",
        product_description:"Care Instructions: Machine wash",
        product_rating:"4",
        product_rating_count:"979",
        product_img: "https://m.media-amazon.com/images/I/51tcflY-fNL._AC_UL480_FMwebp_QL65_.jpg",
        product_discount_price: "420.00",
        product_price: "1200.00",
        product_discount_percentage: "65 ",
        product_color:"White",
        product_size:"Slim fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1166",
        product_name:"AELOMART Women's Top(AWT6088-P_Yellow)",
        product_description:"Care Instruction:wash only separately||Fabric :100  Cotton fabric",
        product_rating:"4",
        product_rating_count:"55",
        product_img: "https://m.media-amazon.com/images/I/71K3zXFkxDL._AC_UL480_FMwebp_QL65_.jpg",
        product_discount_price: "399.00",
        product_price: "1599.00",
        product_discount_percentage: "75 ",
        product_color:"Yellow",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1167",
        product_name:"hasmi Casual Square Neck Full Sleeves Western Stylish Women's Tops",
        product_description:"Care Instructions: Machine Wash||Materials: 95  Polyester, 5  Spandex; stretchable fabric || Sleeve:long sleeve|| Neck Type:square neck",
        product_rating:"3.5",
        product_rating_count:"424",
        product_img: "https://m.media-amazon.com/images/I/71ooEN04ZHL._AC_UL480_FMwebp_QL65_.jpg",
        product_discount_price: "349.00",
        product_price: "1599.00",
        product_discount_percentage: "78 ",
        product_color:"Black",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1168",
        product_name:"Dream Beauty Fashion Bishop Sleeves Square Neck Slim Top Polyester Blend",
        product_description:"Care Instructions: Hand Wash Only|| Sleeves : Bishop||Neck:Square",
        product_rating:"4.5",
        product_rating_count:"61",
        product_img: "https://m.media-amazon.com/images/I/41CxywOyyML._AC_UL480_FMwebp_QL65_.jpg",
        product_discount_price: "299.00",
        product_price: "799.00",
        product_discount_percentage: "63 ",
        product_color:"Frost White",
        product_size:"Slim fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1169",
        product_name:" SIRIL Women's Crepe Printed Top",
        product_description:"Care Instructions: Machine Wash||Fabric : Crepe | Inner Fabric||work: printed||Sleeve:Sleeveless ",
        product_rating:"4",
        product_rating_count:"29",
        product_img: "https://m.media-amazon.com/images/I/71TNhGWphrL._AC_UL480_FMwebp_QL65_.jpg",
        product_discount_price: "349.00",
        product_price: "1230.00",
        product_discount_percentage: "72",
        product_color:"Multicolour",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1170",
        product_name:"AELOMART Women's Top(AWT6044-Pn_Multicolour)",
        product_description:"Care Instructions: Machine Wash ||Neck: Square",
        product_rating:"4",
        product_rating_count:"305",
        product_img: "https://m.media-amazon.com/images/I/611E1a7ZM5L._AC_UL480_FMwebp_QL65_.jpg",
        product_discount_price: "399.00",
        product_price: "1599.00",
        product_discount_percentage: "75",
        product_color:"Multicolour",
        product_size:"Regular fit",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1171 ",
        product_name:"Jeans",
        product_description:"",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT8jWgP9boSZS4v8nPzXLNeNSffxOn45VF0iWY_Q06su-isOZ7VOx776zOKsrFqHM2anBW5vTaty9GIwVC7BjnZAj9t5uwznDwHzYIg9w&usqp=CAE",
        product_price: "799",
        product_discount_price: "",
        product_discount_percenteage: "",
        product_color:"light blue",
        product_size:"28",
        recentrly_view:true,
        trending_product:true
    },

      {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1172 ",
        product_name:"Skiny-Jeans",
        product_description:"‘Fit like a glove’ is an expression that one can definitely use while describing skinny types of jeans for girls! They hug your curves perfectly, and are practically all-rounders. Whether it’s a shirt or a t-shirt, a blouse or a kurti and everything in between; skinny jeans do it all and do it well!",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://images.bewakoof.com/web/Types-Of-Jeans-For-Girls-bewakoof-blog-1-1613652294.jpg",
        product_price: "1299",
        product_discount_price: "1100",
        product_discount_percenteage: "",
        product_color:"light blue",
        product_size:"28",
        recentrly_view:true,
        trending_product:true
    },

    
      {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1173 ",
        product_name:"Skiny-Jeans",
        product_description:"‘Fit like a glove’ is an expression that one can definitely use while describing skinny types of jeans for girls! They hug your curves perfectly, and are practically all-rounders. Whether it’s a shirt or a t-shirt, a blouse or a kurti and everything in between; skinny jeans do it all and do it well!",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://images.bewakoof.com/web/Types-Of-Jeans-For-Girls-bewakoof-blog-2-1613652295.jpg",
        product_price: "1299",
        product_discount_price: "1100",
        product_discount_percenteage: "",
        product_color:"Dark blue",
        product_size:"28",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1174 ",
        product_name:"Low Waist Jeans",
        product_description:"Low-slung denims are back in fashion, as you may have noticed by now! This doesn’t go to say that high-waisted ones aren’t the ‘it thing’ anymore, but it just means that in the world of all types of jeans, each one is a hero and takes center stage.",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://images.bewakoof.com/web/Types-Of-Jeans-For-Girls-bewakoof-blog-3-1613652295.jpg",
        product_price: "1699",
        product_discount_price: "1400",
        product_discount_percenteage: "",
        product_color:"Dark blue",
        product_size:"29",
        recentrly_view:true,
        trending_product:true
    },

      {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1175 ",
        product_name:"Boyfriend Jeans",
        product_description:"When boyfriend jeans hit us, we couldn’t believe that denims could offer the same comfort as our favorite lounge pants and be uber-stylish for the outdoorsNo, it’s nothing like slipping into your boyfriend’s jeans, but more about keeping it baggy yet fashionable",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://images.bewakoof.com/web/Types-Of-Jeans-For-Girls-bewakoof-blog-5-1613652296.jpg",
        product_price: "1699",
        product_discount_price: "1599",
        product_discount_percenteage: "",
        product_color:"Gray Blue",
        product_size:"27",
        recentrly_view:true,
        trending_product:true
    },

    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1176",
        product_name: "High Waisted JEans",
        product_description:"The exact opposite of everything low-hung jeans have to offer, high waisted ones are something of a sensation in the fashion world.",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://images.bewakoof.com/web/Types-Of-Jeans-For-Girls-bewakoof-blog-7-1613652297.jpg",
        product_price: "1699",
        product_discount_price: "1400",
        product_discount_percenteage: "",
        product_color:"Dark blue",
        product_size:"28",
        recentrly_view:true,
        trending_product:true
    },

    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1177",
        product_name : "Overalls" ,
        product_description:"The exact opposite of everything low-hung jeans have to offer, high waisted ones are something of a sensation in the fashion world.",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://images.bewakoof.com/web/Types-Of-Jeans-For-Girls-bewakoof-blog-9-1613652298.jpg",
        product_price: "1699",
        product_discount_price: "1400",
        product_discount_percenteage: "",
        product_color:"Dark blue",
        product_size:"28",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1178",
        product_name : "Capri Pants", 
        product_description:"Capris might not be flattering for all body types though, so be sure to try them out beforehand to see if they suit you, or if you should lean towards other types of jeans for girls instead.",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://images.bewakoof.com/web/Types-Of-Jeans-For-Girls-bewakoof-blog-11-1613652299.jpg",
        product_price: "1299",
        product_discount_price: "999",
        product_discount_percenteage: "",
        product_color:"blue",
        product_size:"28",
        recentrly_view:true,
        trending_product:true
    },
{
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1179",
        product_name : "Flared Jeans", 
        product_description:"Capris might not be flattering for all body types though, so be sure to try them out beforehand to see if they suit you, or if you should lean towards other types of jeans for girls instead.",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://images.bewakoof.com/web/Types-Of-Jeans-For-Girls-bewakoof-blog-13-1613652300.jpg",
        product_price: "1299",
        product_discount_price: "999",
        product_discount_percenteage: "",
        product_color:"blue",
        product_size:"28",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1180",
        product_name :"Ripped Jeans", 
        product_description:"Capris might not be flattering for all body types though, so be sure to try them out beforehand to see if they suit you, or if you should lean towards other types of jeans for girls instead.",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://images.bewakoof.com/web/Types-Of-Jeans-For-Girls-bewakoof-blog-17-1613652302.jpg",
        product_price: "1199",
        product_discount_price: "999",
        product_discount_percenteage: "",
        product_color:"blue",
        product_size:"28",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1181",
        product_name:"Centrino 5631 Casual-Men's Shoes",
        product_description:"CENTRINO CASUAL SHOES MATERIAL: SYNTHETIC MATERIAL. THESE SHOES ARE MADE UP OF HIGH QUALITY SYNTHETIC MATERIAL STAYS STRONG AND DURABLE - MEANING THE SHOES WILL LAST MUCH LONGER. LIFESTYLE: FORMAL / BUSINESS. PAIR THESE STYLISH CENTRINO SHOES WITH YOUR SHIRT & TROUSERS FOR THAT PERFECT LOOK. OFFICE WEAR, OFFICE SHOES, FORMAL SHOES, SLIP-ON, BUSINESS SHOES. CLOSURE: SLIP-ON. CENTRINO SHOES ARE HAND-CRAFTED FOR THAT PERFECT FIT. PERFORATED INSOLE LETS AIR PASS THROUGH THE MATERIAL. THIS IS GREAT FOR LEATHER SHOES BECAUSE THE MATERIAL LETS AIR IN TO COOL YOUR FEET AND STOP THEM FROM SMELLING. FIT: COMFORT FIT. CENTRINO ENDORSES STYLE THAT STRIKES A FINE BALANCE BETWEEN THE CLASSIC AND THE MODERN, THE DISCREET AND THE BOLD WITH GOOD TASTE BEING THE ONLY CRITERION FOR SELECTION. CARE INSTRUCTIONS: ALLOW YOUR PAIR OF SHOES TO AIR ON A REGULAR BASIS. THIS HELPS THEM RETAIN THEIR NATURAL SHAPE; DRY SHOES AT ROOM TEMPERATURE ONLY. EXCESSIVE EXPOSURE TO SUN, WILL CAUSE THE LEATHER TO SHRINK, WRINKLE, HARDEN, DRY, AND CRACK. USE SHOE BAGS TO PREVENT ANY STAINS OR MILDEW; DUST ANY DRY DIRT FROM THE SURFACE USING A CLEAN CLOTH. FOR MENS",
        product_rating:"4.0",
        product_rating_count:"675",
        product_img: "https://m.media-amazon.com/images/I/71fj3YjhqoL._UY695_.jpg",
        product_price: "1799",
        product_discount_price: "799",
        product_discount_percentage: "56",
        product_color:"Blue",
        product_size:"9UK",
        recently_view:true,
        trending_product:true,
    },


    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1182",
        product_name:"FLITE Men's Flip Flop",
        product_description:"Sparx Presents footwear range that Will Keep Your Feet At Great Ease, While You walk, run or work out in the Gym. These Are Light In Weight, Flexible And Very Comfortable To Wear As Well.",
        product_rating:"3.0",
        product_rating_count:"500",
        product_img: "https://m.media-amazon.com/images/I/91RIz6UeU0L._UY695_.jpg",
        product_price: "800",
        product_discount_price: "400",
        product_discount_percentage: "50",
        product_color:"Blue",
        product_size:"7UK",
        recently_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1183",
        product_name:"ASIAN Men's Wonder-13 Sports Running Shoes",
        product_description:"Exclusive design and durable materials every step feels light and breezy. Breathable, free-moving fabrics which adjust according to your foot and creates an astoundingly easy-going experience.",
        product_rating:"4.0",
        product_rating_count:"500",
        product_img: "https://m.media-amazon.com/images/I/61Uh7P5bIUL._SY695._SX._UX._SY._UY_.jpg",
        product_price: "1000",
        product_discount_price: "499",
        product_discount_percentage: "50",
        product_color:"Black",
        product_size:"8UK",
        recently_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1184",
        product_name:"ASIAN Men's Running Shoes for Men I Sport Shoes for Boys with Beads Technology Sole for Extra Jump I Memory Foam Insole Casual Shoes for Men",
        product_description:"The outsoles are made by an air cushion, doubling the effect of shock absorption. Besides, these shoes perform excellent in durability and are also slip resistant. It provides push cushioning comfort for foot pain relief and helps relieve pressure while conforming to your every step",
        product_rating:"4.0",
        product_rating_count:"807",
        product_img: "https://m.media-amazon.com/images/I/617Gd+HQQQL._UY695_.jpg",
        product_price: "2000",
        product_discount_price: "999",
        product_discount_percentage: "50",
        product_color:"White",
        product_size:"8UK",
        recently_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1185",
        product_name:"ASIAN Men's Running Shoes for Men I Sport Shoes for Boys with Beads Technology Sole for Extra Jump I Memory Foam Insole Casual Shoes for Men",
        product_description:"The outsoles are made by an air cushion, doubling the effect of shock absorption. Besides, these shoes perform excellent in durability and are also slip resistant. It provides push cushioning comfort for foot pain relief and helps relieve pressure while conforming to your every step",
        product_rating:"4.0",
        product_rating_count:"807",
        product_img: "https://m.media-amazon.com/images/I/71+8xHNsdHL._UX695_.jpg",
        product_price: "2000",
        product_discount_price: "999",
        product_discount_percentage: "50",
        product_color:"White",
        product_size:"8UK",
        recently_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1186",
        product_name:"Neeman's ReLive Knit Casual Lace Up Sneakers for Men | Padded Insole for Extra Support, Stylish Shoes for Boys",
        product_description:"Elevate your style with this classy pair of Casual Shoe from the house of ZOVIM brand. Featuring a contemporary refined design with exceptional comfort, this pair is perfect to give your quintessential dressing an upgrade.",
        product_rating:"4.5",
        product_rating_count:"2345",
        product_img: "https://m.media-amazon.com/images/I/71IxVUq8HTL._SX695._SX._UX._SY._UY_.jpg",
        product_price: "3299",
        product_discount_price: "2639",
        product_discount_percentage: "20",
        product_color:"Red",
        product_size:"9UK",
        recently_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1186",
        product_name:"ROCKFIELD Men's Blue Denim Sneakers Casual Shoes",
        product_description:"Elevate your style with this classy pair of Casual Shoe from the house of ZOVIM brand. Featuring a contemporary refined design with exceptional comfort, this pair is perfect to give your quintessential dressing an upgrade.",
        product_rating:"4.0",
        product_rating_count:"779",
        product_img: "https://m.media-amazon.com/images/I/81E0uiZHnOL._UY695_.jpg",
        product_price: "1499",
        product_discount_price: "749",
        product_discount_percentage: "50",
        product_color:"Blue",
        product_size:"8UK",
        recently_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1186",
        product_name:"Zovim Men's Casual Shoes",
        product_description:"Elevate your style with this classy pair of Casual Shoe from the house of ZOVIM brand. Featuring a contemporary refined design with exceptional comfort, this pair is perfect to give your quintessential dressing an upgrade.",
        product_rating:"4.0",
        product_rating_count:"779",
        product_img: "https://m.media-amazon.com/images/I/81UKVfIck-L._UX695_.jpg",
        product_price: "3895",
        product_discount_price: "2726",
        product_discount_percentage: "30",
        product_color:"Blue",
        product_size:"8UK",
        recently_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1187",
        product_name:"Woodland Boys Moccasins",
        product_description:"Genuine leather Casual products.",
        product_rating:"4.0",
        product_rating_count:"999",
        product_img: "https://m.media-amazon.com/images/I/71wbf76WYPL._UX695_.jpg",
        product_price: "3995",
        product_discount_price: "2596",
        product_discount_percentage: "30",
        product_color:"Black",
        product_size:"9UK",
        recently_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1188",
        product_name:"Zovim Men's Casual Shoeseeken Black Canvas Lightweight Casual Shoes for Men (by Paragon)",
        product_description:"A pair of high ankle classic chukka canvas shoe is the best companion to be worn at college festivals; while jumping puddles & while running away from then mundane. Glide through the week in India's first lightweight canvas shoes. Goes well with Jeans / Denims",
        product_rating:"4.0",
        product_rating_count:"999",
        product_img: "https://m.media-amazon.com/images/I/615VR2lCp5L._UY695_.jpg",
        product_price: "1499",
        product_discount_price: "1275",
        product_discount_percentage: "15",
        product_color:"Gray",
        product_size:"9UK",
        recently_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1189",
        product_name:"The diamond-encrusted Tom Ford shoes were worn by Nick Cannon on America's Got Talent.",
        product_description:"The most expensive shoes in the world are their own rightful category in the luxury market. Often sold off at auctions rather than at retailers, these shoes are much more than footwear. The most expensive shoes can be a slice of history or even require a safe to be stored in",
        product_rating:"5.0",
        product_rating_count:"21789",
        product_img: "https://footwearnews.com/wp-content/uploads/2019/02/diamond_loafers-1.jpg",
        product_price: "159147000",
        product_discount_price: "158147000",
        product_discount_percentage: "2",
        product_color:"Silver",
        product_size:"9UK",
        recently_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1190",
        product_name:"Michael Jordan’s Air Jordan 12s",
        product_description:"The sneakers once belonged to former Chicago Bulls player Michael Jordan. The all-star basketball player wore the shoes during the famous Flu Game",
        product_rating:"5.0",
        product_rating_count:"1456",
        product_img: "https://footwearnews.com/wp-content/uploads/2016/05/air-jordan-12-flu-game-1.jpg",
        product_price: "8336517",
        product_discount_price: "7935673",
        product_discount_percentage: "5",
        product_color:"Red",
        product_size:"9UK",
        recently_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1191",
        product_name:"Azai By Nykaa ",
        product_description:" This Green Jewellery Colored Stone Set by Azai is all you need to get the spotlight on you at any wedding you step into. The set includes a necklace and a pair of earrings.",
        product_rating:"4.9",
        product_rating_count:"11223",
        product_img: "https://m.media-amazon.com/images/I/41kOJDFXLNL._UY695_.jpg",
        product_price: "4563",
        product_discount_price: "1,597",
        product_discount_percentage: "65 ",
        product_color:"Golden",
        product_size:"NA",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1192",
        product_name:"Azai By Nykaa Fashion Latest Silver & Mint Green Jewellery Set For Women",
        product_description:" This Green Jewellery Colored Stone Set by Azai is all you need to get the spotlight on you at any wedding you step into. The set includes a necklace and a pair of earrings.Team it up with a gorgeous and elegant saree paired with heels and you will be the ultimate showstopper wherever you go.",
        product_rating:"4.7",
        product_rating_count:"2727",
        product_img: "https://m.media-amazon.com/images/I/61GaOnu4Z+L._UY695_.jpg",
        product_price: "2,849.00",
        product_discount_price: "997",
        product_discount_percentage: "65 ",
        product_color:"Silver",
        product_size:"NA",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1193",
        product_name:"Harshitha's Jewelry Metal Women's Bangles(HRSTJ004_P)",
        product_description:"This product is made by Women entrepreneurs from Tamil Nadu who are part of Amazon Saheli program",
        product_rating:"4.1",
        product_rating_count:"12897",
        product_img: "https://m.media-amazon.com/images/I/61zjuf+rygL._UY575_.jpg",
        product_price: "599.00",
        product_discount_price: "499.00",
        product_discount_percentage: "17  ",
        product_color:"	Multicolor",
        product_size:"NA",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1194",
        product_name:"Brado Jewellery Rose Gold Plated American Diamond Black Duck Necklace Golden Chain for Women & Girls (Yellow)",
        product_description:" Brado Jewellery is renowned by its classic and playful designs.Choose the divine jewelry to express your love with us. A perfect gift for your soul mate. The Perfect touch of sparkle. Brado Jewellery Necklace is a classic piece that never goes out of style. This solitaire Necklace is a simple, shiny treat that you will wear forever. A perfect gift on the occasions like Wedding, Valentine’s day, Birthdays etc.",
        product_rating:"3.0",
        product_rating_count:"2234",
        product_img: "https://m.media-amazon.com/images/I/71upm73OSlS._UY575_.jpg",
        product_price: "999",
        product_discount_price: "119.00",
        product_discount_percentage: "88 ",
        product_color:"White",
        product_size:"NA",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1195",
        product_name:"Yobella",
        product_description:"Never allow your fashion jewellery to come in contact with harsh chemicals, oils, nor spray perfumes directly on them. This will cause the jewellery to fade, discolour, or even ruin them completely. And we wouldn’t want that!",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://m.media-amazon.com/images/I/710dnChlpcS._UY695_.jpg",
        product_price: "1,999.00",
        product_discount_price: "197.00",
        product_discount_percentage: "90 ",
        product_color:"Multicolor",
        product_size:"NA",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1196",
        product_name:"YouBella Jewellery Silver and Gold Stylish Adjustable Bracelet Combo of Two for Girls and Women",
        product_description:"Never allow your fashion jewellery to come in contact with harsh chemicals, oils, nor spray perfumes directly on them. This will cause the jewellery to fade, discolour, or even ruin them completely. And we wouldn’t want that!",
        product_rating:"3.9",
        product_rating_count:"232434",
        product_img: "https://m.media-amazon.com/images/I/61-FgEVebgL._UY575_.jpg",
        product_price: "1,199.00",
        product_discount_price: "245.00",
        product_discount_percentage: "80 ",
        product_color:"Golden and silver",
        product_size:"NA",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1197",
        product_name:"MMTC-PAMP 24k (999.9) 10 gm Goddess Lakshmi Yellow Gold Coin",
        product_description:"999.9 / 24K PUREST GOLD: Crafted from 999.9 / 24K purest gold, this gold coin goes through rigorous refining and purification process to ensure you get the purest piece of metal. We go beyond 999.9 to give you 999.9+ purity",
        product_rating:"4.5",
        product_rating_count:"23192",
        product_img: "https://m.media-amazon.com/images/I/71LLiqiFh6L._UY575_.jpg",
        product_price: "65,960.00",
        product_discount_price: "56,120.00",
        product_discount_percentage: "15 ",
        product_color:"Gold",
        product_size:"NA",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1198",
        product_name:"Shining Diva Fashion 18k Gold and Silver Plated Adjustable Crystal Cuff Bracelet for Women and Girls",
        product_description:"Shining diva is a well known brand across fashion jewellery sector shining diva products are preferred by many designers, stars and celebrities shining diva fashion jewelry believes in making beauty and fashion a part of everybody's life",
        product_rating:"3.8",
        product_rating_count:"92892",
        product_img: "https://m.media-amazon.com/images/I/714fIkdqr7L._UY575_.jpg",
        product_price:  "1,999.00",
        product_discount_price: "299.00",
        product_discount_percentage: "85 ",
        product_color:"Other Color",
        product_size:"NA",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1199",
        product_name:"Yellow Chimes Swarovski Elements Deep Ocean Love Hearts Bracelet for Women and Girls",
        product_description:"This Soft Blue Swarovski Crystal Special collection Hearts Joining Bangle radiates feminine romance. Shimmering in clear crystal pavé, it is embellished with a sparkling Blue Hearts, It is good to add moods to Love, and beauty to any Outfit. The adjustable closure ensures a secure fit. The Oval shape of bracelet keep the main part in front and even makes it stick to hand perfectly. The diameter is between 5-6 cm.",
        product_rating:"3.4",
        product_rating_count:"23871",
        product_img: "https://m.media-amazon.com/images/I/61Yi-0OfYDL._UY575_.jpg",
        product_price: " 5,999.00",
        product_discount_price: "1,499.00",
        product_discount_percentage: "75 ",
        product_color:"Blue",
        product_size:"NA",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1120",
        product_name:"GANESHAGEMS (इक्क्क्क़ मुखी रुद्राक्ष) Genuine Color Nepali Beads 21 Mukhi Rudraksha Original Certified by Reputed Lab for Men & Women",
        product_description:"Twenty One Face Rudraksha Is Also Known As Kubera Rudraksha.",
        product_rating:"4.1",
        product_rating_count:"12324",
        product_img: "https://m.media-amazon.com/images/I/41lbuBlxLLL.jpg",
        product_price: "2,62,000.00",
        product_discount_price: "1,31,000.00",
        product_discount_percentage: "50 ",
        product_color:"Brown",
        product_size:"NA",
        recently_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "101",
        product_id: "1001",
        product_name:"Girl Frock",
        product_description:"Mirrow Trade Girl's Party Wear Maxi Gown",
        product_rating:"3.8",
        product_rating_count:"47",
        product_img: "https://n2.sdlcdn.com/imgs/k/c/v/Mirrow-Trade-Girl-s-Party-SDL488767720-1-4f6c7.jpeg",
        product_price: "1999",
        product_discount_price: "419",
        product_discount_percenteage: "79%",
        product_color:"Green",
        product_size:"3-6 Years",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "101",
        product_id: "1102",
        product_name:"Lehenga Cholis For Girls",
        product_description:"RABDI Semi-Stitched phantom satin Kids girl's Lehenga Choli",
        product_rating:"3.7",
        product_rating_count:"49",
        product_img: "https://n2.sdlcdn.com/imgs/k/e/0/RABDI-Semi-Stitched-phantom-satin-SDL456693024-1-c284a.jpg",
        product_price: "1599",
        product_discount_price: "649",
        product_discount_percenteage: "59%",
        product_color:"RoyalBlue",
        product_size:"4-5 Years",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "101",
        product_id: "1103",
        product_name:"Jeans for Girls",
        product_description:"KUNDAN Girl's Dark Blue & Black Slim Fit Jeans ( Pack of 2 )",
        product_rating:"4.0",
        product_rating_count:"4",
        product_img: "https://n1.sdlcdn.com/imgs/j/x/i/KUNDAN-Girl-s-Dark-Blue-SDL311050500-1-15e1d.jpg",
        product_price: "1998",
        product_discount_price: "775",
        product_discount_percenteage: "61%",
        product_color:"Multi",
        product_size:"4-5 Years",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "101",
        product_id: "1104",
        product_name:"Top & Bottom Sets",
        product_description:"Arshia Fashions - Blue Denim Boy's Shirt & Jeans ( Pack of 1 )",
        product_rating:"4.1",
        product_rating_count:"72",
        product_img: "https://n1.sdlcdn.com/imgs/k/i/w/Arshia-Fashions-Blue-Denim-Boy-SDL030124815-1-c4eed.jpg",
        product_price: "2399",
        product_discount_price: "875",
        product_discount_percenteage: "64%",
        product_color:"Blue",
        product_size:"2-3 Years",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "101",
        product_id: "1105",
        product_name:"Bottom Wear",
        product_description:"Rydho - Green Cotton Blend Boy's Trackpant ( Pack of 1 )",
        product_rating:"4.0",
        product_rating_count:"24",
        product_img: "https://n3.sdlcdn.com/imgs/k/i/t/Rydho-Green-Cotton-Blend-Boy-SDL534086504-1-bae6b.jpg",
        product_price: "999",
        product_discount_price: "359",
        product_discount_percenteage: "64%",
        product_color:"Green",
        product_size:"5-6 Years",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "101",
        product_id: "1106",
        product_name:"Ethnicwear",
        product_description:"Boys Festive & Party Kurta and Churidar Set",
        product_rating:"4.0",
        product_rating_count:"243",
        product_img: "https://n1.sdlcdn.com/imgs/k/i/o/Boys-Festive-Party-Kurta-and-SDL504170827-1-bd242.jpg",
        product_price: "999",
        product_discount_price: "329",
        product_discount_percenteage: "67%",
        product_color:"Blood Red",
        product_size:"2-3 Years",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "101",
        product_id: "1107",
        product_name:"Nightwear",
        product_description:"NITE FLITE Boys' Tiger Safari Cotton Nightwear | Top and Pyjama Set (Mustard & Navy Blue,2)",
        product_rating:"4.3",
        product_rating_count:"18",
        product_img: "https://n2.sdlcdn.com/imgs/j/q/b/NITE-FLITE-Boys-Tiger-Safari-SDL773640661-1-09e91.jpg",
        product_price: "599",
        product_discount_price: "489",
        product_discount_percenteage: "18%",
        product_color:"Multi Color",
        product_size:"2-3 Years",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "101",
        product_id: "1108",
        product_name:"Top & Bottom Sets",
        product_description:"Boys Kids Wear",
        product_rating:"5.0",
        product_rating_count:"1",
        product_img: "https://n2.sdlcdn.com/imgs/k/i/4/Boys-Kids-Wear-SDL836122617-1-832ab.jpg",
        product_price: "999",
        product_discount_price: "259",
        product_discount_percenteage: "74%",
        product_color:"Blue",
        product_size:"12-18 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "101",
        product_id: "1109",
        product_name:"Rompers & Body Suits",
        product_description:"Sathiyas Baby Rompers(Pack of 2)",
        product_rating:"4.2",
        product_rating_count:"32",
        product_img: "https://n2.sdlcdn.com/imgs/k/i/u/Sathiyas-Baby-Rompers-Pack-of-SDL305562647-1-07d61.jpg",
        product_price: "599",
        product_discount_price: "239",
        product_discount_percenteage: "60%",
        product_color:"Grey",
        product_size:"0-3 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "101",
        product_id: "1110",
        product_name:"Bottom Wear",
        product_description:"BUMZEE Yellow & Blue Printed Baby Boys Shorts Pack Of 4 Age - 3-6 Months",
        product_rating:"5.0",
        product_rating_count:"1",
        product_img: "https://n3.sdlcdn.com/imgs/k/d/i/BUMZEE-Yellow-Blue-Printed-Baby-SDL747849193-1-1e844.jpg",
        product_price: "1049",
        product_discount_price: "439",
        product_discount_percenteage: "58%",
        product_color:"Yellow",
        product_size:"3-6 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "102",
        product_id: "1111",
        product_name:"Robot Car",
        product_description:"Robot Car 2 in 1 Robot Car (Battery Operated) 2 in 1 Transform with Bright Lights and Music,(Multi-colour)",
        product_rating:"3.8",
        product_rating_count:"13",
        product_img: "https://n1.sdlcdn.com/imgs/j/u/f/Robot-Car-2-in-1-SDL267295728-1-41b30.jpeg",
        product_price: "400",
        product_discount_price: "40",
        product_discount_percenteage: "10%",
        product_color:"Yellow",
        product_size:"Small",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "102",
        product_id: "1112",
        product_name:"Walkie Talkie",
        product_description:"Red Ballons Super Power Communication Wireless Portable InterPhone Walkie Talkie Set for Kids with LCD Display -2",
        product_rating:"4.8",
        product_rating_count:"126",
        product_img: "https://n1.sdlcdn.com/imgs/i/q/o/Red-Ballons-Super-Power-Communication-SDL704191479-1-aaafc.jpeg",
        product_price: "500",
        product_discount_price: "50",
        product_discount_percenteage: "10%",
        product_color:"Black",
        product_size:"Small",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "102",
        product_id: "1113",
        product_name:"Air Gun",
        product_description:"Peshkar Baby Metal Air Gun & 100 Pallets (BLACK)",
        product_rating:"4.8",
        product_rating_count:"16",
        product_img: "https://n4.sdlcdn.com/imgs/k/h/z/Peshkar-Baby-Metal-Air-Gun-SDL223386643-1-56b0c.jpg",
        product_price: "1000",
        product_discount_price: "500",
        product_discount_percenteage: "50%",
        product_color:"Black",
        product_size:"Small",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "102",
        product_id: "1114",
        product_name:"Steering Drive",
        product_description:"NHR MCL Rideon Musical Ride on Car with Front and Rear Colors, Steering Drive, Perfect for Kids (1 to 3 Years , Blue)",
        product_rating:"5",
        product_rating_count:"67",
        product_img: "https://n3.sdlcdn.com/imgs/k/e/q/NHR-MCL-Rideon-Musical-Ride-SDL898283240-1-6526e.jpg",
        product_price: "2000",
        product_discount_price: "500",
        product_discount_percenteage: "25%",
        product_color:"Blue",
        product_size:"Small",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "102",
        product_id: "1115",
        product_name:"Binoculars",
        product_description:"Omak binoculars doorbeen outdoor observing binoculars telescope toy /military color/folding binoculars-Multi color",
        product_rating:"3",
        product_rating_count:"56",
        product_img: "https://n1.sdlcdn.com/imgs/k/d/p/Omak-binoculars-doorbeen-outdoor-observing-SDL104859545-1-d26ed.jpg",
        product_price: "400",
        product_discount_price: "40",
        product_discount_percenteage: "10%",
        product_color:"Black",
        product_size:"Small",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "102",
        product_id: "1116",
        product_name:"TEDDY BEAR",
        product_description:"TEDDY BEAR red teddy bear",
        product_rating:"2",
        product_rating_count:"67",
        product_img: "https://n2.sdlcdn.com/imgs/i/f/x/TEDDY-BEAR-red-teddy-bear-SDL953520679-1-26a56.jpeg",
        product_price: "200",
        product_discount_price: "100",
        product_discount_percenteage: "50%",
        product_color:"Red",
        product_size:"Medium",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "102",
        product_id: "1117",
        product_name:"Writing Pad",
        product_description:"Writing Pads Toy Tablet LCD Graphic Tablet Writing Tablet 8.5 Inch E-Note Pad (Color As Per Availability)",
        product_rating:"4",
        product_rating_count:"89",
        product_img: "https://n2.sdlcdn.com/imgs/k/h/0/Writing-Pads-Toy-Tablet-LCD-SDL654331098-1-67e59.jpg",
        product_price: "99",
        product_discount_price: "0",
        product_discount_percenteage: "0%",
        product_color:"Black-Blue",
        product_size:"Medium",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "102",
        product_id: "1118",
        product_name:"Piggy Bank",
        product_description:"Wooden Handicrafts Piggy Bank Kids Toy | Handmade Money Bank | Gullak for Kids | Coin Box Birthday Gift for Kids and",
        product_rating:"4",
        product_rating_count:"555",
        product_img: "https://n1.sdlcdn.com/imgs/k/i/m/SUNTAP-Wood-Brown-None-Piggy-SDL474052419-1-e3d8f.jpeg",
        product_price: "300",
        product_discount_price: "60",
        product_discount_percenteage: "20%",
        product_color:"Wooden",
        product_size:"Small",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "102",
        product_id: "1119",
        product_name:"Baby Doll",
        product_description:"Toyshine Sweety Realistic Baby Doll 6 inches , Non-Toxic Vinyl, Braided Hair, Mutli-Color",
        product_rating:"4",
        product_rating_count:"66",
        product_img: "https://n3.sdlcdn.com/imgs/k/b/h/Toyshine-Sweety-Realistic-Baby-Doll-SDL244808007-2-67757.jpg",
        product_price: "50",
        product_discount_price: "0",
        product_discount_percenteage: "0%",
        product_color:"Skin",
        product_size:"Small",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "102",
        product_id: "1120",
        product_name:"Building Bricks",
        product_description:"Adichai 120 Plus Pieces Multicolor Small Building Bricks and Blocks for Kids with Wheel Age 3+, Smart Activity Fun and",
        product_rating:"4",
        product_rating_count:"66",
        product_img: "https://n2.sdlcdn.com/imgs/k/j/a/Adichai-120-Plus-Pieces-Multicolor-SDL399846405-1-edd21.jpg",
        product_price: "100",
        product_discount_price: "10",
        product_discount_percenteage: "10%",
        product_color:"Multi-Color",
        product_size:"Small",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "103",
        product_id: "1121",
        product_name: "Pencil Boxes ",
        product_description: "Unicorn Fur Coin Pouch for Girls Pouch Mini Pouch for Cards Holder Mini Purse for Girls Unicorn Fur Zipper Closer Coin Pouch Soft and Cute Pouch (Pack of 4)",
        product_rating: "3.4",
        product_rating_count: "24",
        product_img: "https://n4.sdlcdn.com/imgs/k/j/c/Unicorn-Fur-Coin-Pouch-for-SDL965743797-1-97eb9.jpg",
        product_price: "899",
        product_discount_price: "349",
        product_discount_percenteage: "61%",
        product_color: "pink",
        product_size: "",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "103",
        product_id: "1122",
        product_name: "Files Folders ",
        product_description: "Kopila Polypropylene Sliding Plastic Bar Project File Folder for A4 Paper Display (Transparent) - Pack of 5 Multi Color",
        product_rating: "4.0",
        product_rating_count: "50",
        product_img: "https://n3.sdlcdn.com/imgs/j/o/k/Kopila-Polypropylene-Sliding-Plastic-Bar-SDL609535927-1-79696.jpg",
        product_price: "499",
        product_discount_price: "159",
        product_discount_percenteage: "68%",
        product_color: "blue",
        product_size: "",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "103",
        product_id: "1123",
        product_name: "calculator",
        product_description: "Jito JT-512 12 Digits with 1 Years Warranty Electronic Calculator (Green)",
        product_rating: "4.5",
        product_rating_count: "15",
        product_img: "https://n3.sdlcdn.com/imgs/j/y/a/Jito-JT-512-12-Digits-SDL486695645-1-8364c.jpg",
        product_price: "499",
        product_discount_price: "319",
        product_discount_percenteage: "36%",
        product_color: "green",
        product_size: "",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "103",
        product_id: "1124",
        product_name: "Diaries & Planners",
        product_description: "COI To live Notebooks & Pocket Size Diary Set of 5.",
        product_rating: "3.8",
        product_rating_count: "66",
        product_img: "https://n2.sdlcdn.com/imgs/j/s/c/COI-To-live-Notebooks-Pocket-SDL342138382-1-e7e3c.jpg",
        product_price: "599",
        product_discount_price: "169",
        product_discount_percenteage: "72%",
        product_color: "yellow",
        product_size: "",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "103",
        product_id: "1125",
        product_name: "Notebooks Writing Pads ",
        product_description: "FSN-MAGIC PRACTICE COPYBOOK Number Tracing Book for Preschoolers with Pen, Magic Calligraphy Copybook Set ( 4 BOOKS + 10 REFILL)",
        product_rating: "4.0",
        product_rating_count: "444",
        product_img: "https://n3.sdlcdn.com/imgs/k/e/8/FSN-MAGIC-PRACTICE-COPYBOOK-Number-SDL508620363-1-9d94e.jpg",
        product_price: "999",
        product_discount_price: "379",
        product_discount_percenteage: "62%",
        product_color: "yellow",
        product_size: "",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "103",
        product_id: "1126",
        product_name: "Photo Paper",
        product_description: "VMS Eco Plus 180 GSM Photo Paper Water Resistant Quick Drying High Glossy Inkjet Photo Paper A4 (210 x 297mm) 180 GSM A4 Photo Paper (Set of 2-20X2 = 40 Sheets)",
        product_rating: "5.0",
        product_rating_count: "1",
        product_img: "https://n4.sdlcdn.com/imgs/i/q/p/VMS-Eco-Plus-180-GSM-SDL607395207-1-aa720.jpg",
        product_price: "440",
        product_discount_price: "419",
        product_discount_percenteage: "5%",
        product_color: "pink",
        product_size: "",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "103",
        product_id: "1127",
        product_name: "Pencil Boxes",
        product_description: "Silicon Big Size Pop It Pencil case for Kids School Pouch for Stationary Storage Pop It Pencil Case Big (MULTICOLOUR)",
        product_rating: "4.8",
        product_rating_count: "8",
        product_img: "https://n4.sdlcdn.com/imgs/k/g/0/Silicon-Big-Size-Pop-It-SDL693593821-1-eb0f8.PNG",
        product_price: "499",
        product_discount_price: "329",
        product_discount_percenteage: "34%",
        product_color: "orange",
        product_size: "",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "103",
        product_id: "1128",
        product_name: "Staplers Punches ",
        product_description: "RAVARIYA GRAPHICS Metal Mesh Stationery Holder / Desk Organizer Stand with 8 Compartments and 1 Drawer for Home and Office",
        product_rating: "3.0",
        product_rating_count: "344",
        product_img: "https://n1.sdlcdn.com/imgs/k/i/v/RAVARIYA-GRAPHICS-Metal-Mesh-Stationery-SDL471626015-1-23d11.jpeg",
        product_price: "999",
        product_discount_price: "775",
        product_discount_percenteage: "22%",
        product_color: "pink",
        product_size: "",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "103",
        product_id: "1129",
        product_name: "Roller Ball Pens",
        product_description: "Genuine Oculus Athlete-0018A Designer Slim Metal Roller Ball Pen in Red & Black Combination Fitted",
        product_rating: "4.5",
        product_rating_count: "100",
        product_img: "https://n1.sdlcdn.com/imgs/h/t/g/Genuine-Oculus-Athlete-0018A-Designer-SDL065918191-1-11621.jpg",
        product_price: "799",
        product_discount_price: "249",
        product_discount_percenteage: "69%",
        product_color: "red",
        product_size: "",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "103",
        product_id: "1130",
        product_name: "Diaries & Planners",
        product_description: "COI BLACK CUTE DIARY NOTEBOOK - Vintage Faux Leather A5 Travel Journal for an awesome friendly kids for Stylish girls and boys with Pen.",
        product_rating: "4.4",
        product_rating_count: "444",
        product_img: "https://n2.sdlcdn.com/imgs/j/s/h/COI-BLACK-CUTE-DIARY-NOTEBOOK-SDL691874026-1-77593.jpeg",
        product_price: "1499",
        product_discount_price: "699",
        product_discount_percenteage: "53%",
        product_color: "black",
        product_size: "",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "104",
        product_id: "1131",
        product_name: "Baby Girl Sandals",
        product_description: "Coolz Kids Chu-Chu Sound Musical First Walking Sandals Baby-1 for Baby Boys and Baby Girls Age 1-2.5 Years",
        product_rating: "3.0",
        product_rating_count: "44",
        product_img: "https://n1.sdlcdn.com/imgs/j/v/p/Coolz-Kids-Chu-Chu-Sound-SDL178130563-1-46eaa.jpg",
        product_price: "77",
        product_discount_price: "14",
        product_discount_percenteage: "20%",
        product_color: "Red",
        product_size: "Small",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "104",
        product_id: "1132",
        product_name: "Baby Girl Sports Sandals",
        product_description: "BUNNIES Sports Sandals For Boys & Girls(6 Months To 3 Years",
        product_rating: "1.0",
        product_rating_count: "34",
        product_img: "https://n1.sdlcdn.com/imgs/j/v/r/BUNNIES-Sports-Sandals-For-Boys-SDL819462973-1-f91e5.jpg",
        product_price: "200",
        product_discount_price: "125",
        product_discount_percenteage: "75%",
        product_color: "Wooden",
        product_size: "Small",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "104",
        product_id: "1133",
        product_name: "Baby Back Clogs",
        product_description: "NEOBABY Sling Back Clogs For Boys & Girls",
        product_rating: "5.0",
        product_rating_count: "111",
        product_img: "https://n4.sdlcdn.com/imgs/k/f/g/NEOBABY-Sling-Back-Clogs-For-SDL042274478-1-9f8d3.jpg",
        product_price: "250",
        product_discount_price: "25",
        product_discount_percenteage: "10%",
        product_color: "Purple",
        product_size: "Small",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "104",
        product_id: "1134",
        product_name: "Dancing Shoes",
        product_description: "BUNNIES Loafer Dancing Shoes For Boys And Girls (6 Month - 3 Year",
        product_rating: "4.0",
        product_rating_count: "1161",
        product_img: "https://n1.sdlcdn.com/imgs/j/y/o/BUNNIES-Loafer-Dancing-Shoes-For-SDL047344585-1-69cbc.jpeg",
        product_price: "500",
        product_discount_price: "0",
        product_discount_percenteage: "0%",
        product_color: "Pink",
        product_size: "Small",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "104",
        product_id: "1135",
        product_name: "child care Booties",
        product_description: "LMN child care Booties (Toe to Heel Length - 12 cm, Pink-Black)",
        product_rating: "3.0",
        product_rating_count: "88",
        product_img: "https://n4.sdlcdn.com/imgs/k/b/f/Bootie-SDL098758628-1-f6e9a.jpg",
        product_price: "800",
        product_discount_price: "80",
        product_discount_percenteage: "10%",
        product_color: "Pink",
        product_size: "Small",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "104",
        product_id: "1136",
        product_name: "Sandals",
        product_description: "Peppa Pig by Yellow Bee Island Life Sandals",
        product_rating: "5.0",
        product_rating_count: "777",
        product_img: "https://n4.sdlcdn.com/imgs/k/e/e/Peppa-Pig-by-Yellow-Bee-SDL881171675-1-65d4b.jpg",
        product_price: "1000",
        product_discount_price: "100",
        product_discount_percenteage: "10%",
        product_color: "Orange",
        product_size: "Small",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "104",
        product_id: "1137",
        product_name: "Slip Booties",
        product_description: "Neska Moda Baby Boys And Girls Blue Anti Slip Booties For 0 To 12 Months-BT286",
        product_rating: "2.8",
        product_rating_count: "55",
        product_img: "https://n4.sdlcdn.com/imgs/j/x/6/Neska-Moda-Baby-Boys-And-SDL190437617-1-ffad0.jpeg",
        product_price: "350",
        product_discount_price: "35",
        product_discount_percenteage: "10%",
        product_color: "White",
        product_size: "Small",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "104",
        product_id: "1138",
        product_name: "LED Sneakers",
        product_description: "Hopscotch Baby Boy Mesh Lace Up LED Sneakers in White Color, UK:7 (FAQ-3100440)",
        product_rating: "4.8",
        product_rating_count: "55888",
        product_img: "https://n2.sdlcdn.com/imgs/j/x/6/Hopscotch-Baby-Boy-Mesh-Lace-SDL215956857-1-627c1.jpeg",
        product_price: "650",
        product_discount_price: "130",
        product_discount_percenteage: "20%",
        product_color: "White",
        product_size: "Small",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "104",
        product_id: "1139",
        product_name: " Musical Walking shoes ",
        product_description: "Coolz Kids Chu-Chu Sound Musical First Walking shoes Star-01 for Baby Boys and Baby Girls for 9-24 Months",
        product_rating: "4.9",
        product_rating_count: "775",
        product_img: "https://n2.sdlcdn.com/imgs/j/y/j/Coolz-Kids-Chu-Chu-Sound-SDL126331333-1-b19d3.jpeg",
        product_price: "750",
        product_discount_price: "140",
        product_discount_percenteage: "20%",
        product_color: "Blue",
        product_size: "Small",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "104",
        product_id: "1140",
        product_name: "Clubs Sheos",
        product_description: "Girls Clubs Boys & Girls Lace Sneakers For 6 Months to 15 Months(Blue)",
        product_rating: "2.9",
        product_rating_count: "22",
        product_img: "https://n1.sdlcdn.com/imgs/k/e/5/Girls-Clubs-Boys-Girls-Lace-SDL027175936-1-02097.jpg",
        product_price: "850",
        product_discount_price: "85",
        product_discount_percenteage: "10%",
        product_color: "Blue",
        product_size: "Small",
        recentrly_view: true,
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "105",
        product_id: "1141",
        product_name:"BabyJacket",
        product_description:"Hopscotch Boys and Girls Cotton and Polyetser Full Sleeves Text Printed Jacket in Beige Color For Ages 12-18 Months (YF0-3115334)",
        product_rating:"5.0",
        product_rating_count:"2",
        product_img: "https://n4.sdlcdn.com/imgs/j/w/q/Hopscotch-Boys-and-Girls-Cotton-SDL030439024-1-dff29.jpg",
        product_price: "1109",
        product_discount_price: "575",
        product_discount_percenteage: "48%",
        product_color:"Beige",
        product_size:"12-18 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "105",
        product_id: "1142",
        product_name:"BabyJacket",
        product_description:"Hopscotch Baby Girls Cotton and Polyetser Full Sleeves Solid Long Coat in Pink Color For Ages 18-24 Months (ADX-3771789)",
        product_rating:"4.0",
        product_rating_count:"2",
        product_img: "https://n2.sdlcdn.com/imgs/j/x/i/Hopscotch-Baby-Girls-Cotton-and-SDL698172157-1-59204.jpg",
        product_price: "1839",
        product_discount_price: "1025",
        product_discount_percenteage: "44%",
        product_color:"Pink",
        product_size:"18-24 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "105",
        product_id: "1143",
        product_name:"BabyJacket",
        product_description:"Hopscotch Baby Boys Cotton And Spandex Full Sleeves Solid Jacket in Blue Color For Ages 18-24 Months (YIH-3757747)",
        product_rating:"5.0",
        product_rating_count:"1",
        product_img: "https://n3.sdlcdn.com/imgs/j/y/b/Hopscotch-Baby-Boys-Cotton-And-SDL736463102-1-3dfc1.jpg",
        product_price: "1499",
        product_discount_price: "799",
        product_discount_percenteage: "47%",
        product_color:"Blue",
        product_size:"18-24 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "105",
        product_id: "1144",
        product_name:"BabyJacket",
        product_description:"Hopscotch Baby Girls Polyester Full Sleeves Printed Jacket in Red Color For Ages 6-12 Months (YNG-3817853)",
        product_rating:"5.0",
        product_rating_count:"1",
        product_img: "https://n1.sdlcdn.com/imgs/j/x/4/Hopscotch-Baby-Girls-Polyester-Full-SDL972548357-1-4246b.jpg",
        product_price: "1979",
        product_discount_price: "1199",
        product_discount_percenteage: "39%",
        product_color:"Red",
        product_size:"6-12 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "105",
        product_id: "1145",
        product_name:"BabyJacket",
        product_description:"Black Boys Reversible Gilet Jacket",
        product_rating:"4.8",
        product_rating_count:"4",
        product_img: "https://n1.sdlcdn.com/imgs/j/d/c/Black-Boys-Reversible-Gilet-Jacket-SDL102172151-1-73cb4.jpg",
        product_price: "999",
        product_discount_price: "725",
        product_discount_percenteage: "27%",
        product_color:"Black",
        product_size:"3-6 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "105",
        product_id: "1146",
        product_name:"BabyJacket",
        product_description:"HVM Baby Girls Winter Jacket With Hood",
        product_rating:"4.5",
        product_rating_count:"4",
        product_img: "https://n3.sdlcdn.com/imgs/k/b/e/HVM-Baby-Girls-Winter-Jacket-SDL651776462-1-bac9d.png",
        product_price: "999",
        product_discount_price: "419",
        product_discount_percenteage: "58%",
        product_color:"Blue",
        product_size:"0-3 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "105",
        product_id: "1147",
        product_name:"BabyJacket",
        product_description:"Hopscotch Baby Boys Cotton Full Sleeves Animal Printed Jacket in Black Color For Ages 12-24 Months (GBN-3312321)",
        product_rating:"3.0",
        product_rating_count:"1",
        product_img: "https://n3.sdlcdn.com/imgs/j/x/4/Hopscotch-Baby-Boys-Cotton-Full-SDL581253996-1-7799d.jpg",
        product_price: "699",
        product_discount_price: "439",
        product_discount_percenteage: "37%",
        product_color:"Black",
        product_size:"18-24 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "105",
        product_id: "1148",
        product_name:"BabyJacket",
        product_description:"MINI KLUB Multi Color Jacket For Baby Boy",
        product_rating:"4.0",
        product_rating_count:"1",
        product_img: "https://n4.sdlcdn.com/imgs/j/7/q/MINI-KLUB-Multi-Color-Jacket-SDL815711207-1-ed2bc.jpg",
        product_price: "1299",
        product_discount_price: "539",
        product_discount_percenteage: "59%",
        product_color:"Multi Color",
        product_size:"3-6 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "105",
        product_id: "1049",
        product_name:"BabyJacket",
        product_description:"Hopscotch Boys and Girls Cotton and Polyetser Full Sleeves Text Printed Jacket in Beige Color For Ages 12-18 Months (YF0-3115334)",
        product_rating:"5.0",
        product_rating_count:"2",
        product_img: "https://n4.sdlcdn.com/imgs/j/w/q/Hopscotch-Boys-and-Girls-Cotton-SDL030439024-1-dff29.jpg",
        product_price: "1109",
        product_discount_price: "575",
        product_discount_percenteage: "48%",
        product_color:"Beige",
        product_size:"12-18 Months",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "3",
        sub_cat_id: "105",
        product_id: "1050",
        product_name:"BabyJacket",
        product_description:"Green Boys Hooded Printed Jacket",
        product_rating:"5.0",
        product_rating_count:"1",
        product_img: "https://n3.sdlcdn.com/imgs/j/d/c/Green-Boys-Hooded-Printed-Jacket-SDL561972062-1-7c7f5.jpg",
        product_price: "1199",
        product_discount_price: "875",
        product_discount_percenteage: "27%",
        product_color:"Green",
        product_size:"3-6 Months",
        recentrly_view:true,
        trending_product:true
    }
]

